### ISSUE TITLE
Reboot loop

### ISSUE THREAD

**Issue by fjalves94** [maxis7567/Hackintosh-Dell-7567-OpenCore_Big-Sur#4]
Hello! Thank you for your help. I get reboot loop after first step install. Do you know why? Thanks!

**Comment by maxis7567** [comment]
you must use big sur 11.0 version for installation
i didnt test 11.1 version yet

**Comment by matheusferreira195** [comment]
Any tips on how to download 11.0 version using macrecovery.py? I'm having the same issue using the default BigSur download option from macrecovery.py.

**Comment by maxis7567** [comment]
Use the last version it works

**Comment by maxis7567** [comment]
In case it didn't work use this 
11.0 => http://ir-iphone.org/macappcenter/macos/bigsur/macOS_BigSur_DP1_10.16_20A4299v_MAS.zip

**Comment by matheusferreira195** [comment]
> In case it didn't work use this
> 11.0 => http://ir-iphone.org/macappcenter/macos/bigsur/macOS_BigSur_DP1_10.16_20A4299v_MAS.zip

Couldn't create the installer using win10 using the Opencore tutorial.

But on the other hand, what should we to pre-install? Just generate the MacbookPro14,1 SMBIOS and inject via ProperTree? Maybe I am missing something here.

Just to explain what I tried till here: 
1. Created the installer using opencore tutorial (download .dmg and .chunklist recovery img via macrecovery.py);
2. Modified the key Misc > Security > ScanPolicy  to 0 in config.plist (because when I boot the usb the installer option doens't appear on the selector);
3. Injected the MacbookPro14,1 SMBIOS using GenSMBIOS;
4. The first half of installation did alright, the system reboots on 12 min remaning. I boot in the MacOS Installer created on picker;
5.  Get a little verbose boot, get throw back to opencore picker. Sometimes I get stuck on AAPL: [EB|#LOG:EXIT] and need to restart manually.

Someone else had this problems? Is there something I'm missing?

Important info: I'm trying to install on the 1TB Toshiba HDD that comes with the notebook.

**Comment by maxis7567** [comment]
i didn't try window methods
but you must create bootable usb with GTP schema that has a EFI partition and copy efi folder to it the boot the usb
no need to config anything for installation

**Comment by maxis7567** [comment]
another method you can try is that create a virtual mac os in window and create bootable usb

**Comment by matheusferreira195** [comment]
> another method you can try is that create a virtual mac os in window and create bootable usb

I will give it a try, thanks!

**Comment by matheusferreira195** [comment]
> > another method you can try is that create a virtual mac os in window and create bootable usb
> 
> I will give it a try, thanks!

Updating the case:

Was a wild ride, but I finally got it working. Only issue I have is with the audio, bluetooth works fine, but neither headphone jack or speakers work. But I'm trying to solve it.

What I did to circumvent the boot loop problem was:

1. Created a MacOS VirtualBox. In linux you can get one running pretty easily with [this script](https://github.com/myspaghetti/macos-virtualbox). In WIndows it's more complex, but you can follow tutorials online to create one;

2. Used [this tutorial](https://www.insanelymac.com/forum/topic/321891-create-macos-sierra-usb-installer-in-virtual-box-vm-without-error-copying-files/) to create the installer. Actually, follow @maxis7567  tutorial to create the drive, using the .vmdk explained on the tutorial I linked;

3. For post-install, just follow @maxis7567 tutorial. 

Thanks again @maxis7567, awesome work you did there! Also, I suggest putting this little tutorial on the readme, so people using linux/windows can have some guidance.
